
square_labels = {
    '1': [[True, False, False, False], [True, False, False, True], [False, False, False, False], [False, False, False, False]],
    '2': [[True, False, False, False], [True, False, False, True], [False, False, False, True], [False, False, False, False]],
    '3': [[True, True, False, True], [True, True, True, True], [False, False, False, False], [False, False, False, False]],
    '4': [[False, False, False, False], [True, True, True, False], [False, False, False, True], [False, False, False, False]],
    '5': [[False, False, False, True], [True, False, False, True], [True, False, False, True], [False, False, False, False]],
    '6': [[True, False, False, False], [True, False, False, True], [False, False, False, True], [False, False, False, False]],
    '7': [[False, False, False, False], [True, True, False, False], [True, True, False, True], [False, False, False, False]],
    '8': [[True, True, True, False], [True, True, True, True], [False, False, False, False], [False, False, False, False]],
    '9': [[False, False, False, False], [True, False, False, False], [False, False, True, False], [False, False, False, False]],
    '10': [[True, True, True, False], [True, True, True, True], [False, False, False, False], [False, False, False, False]],
    '11': [[True, False, True, False], [False, False, True, True], [False, False, False, False], [False, False, False, False]],
    '12': [[False, False, False, False], [True, False, False, False], [False, True, True, False], [False, False, False, False]],
    '13': [[True, True, True, True], [False, False, False, False], [False, False, False, False], [False, False, False, False]],
    '14': [[True, True, True, False], [False, False, True, True], [False, False, False, False], [False, False, False, False]],
    '15': [[True, False, False, True], [False, False, True, True], [False, False, False, False], [False, False, False, False]],
    '16': [[True, True, False, False], [False, True, False, True], [False, False, False, True], [False, False, False, False]],
    '17': [[False, False, False, False], [False, True, True, True], [False, False, False, False], [False, False, False, False]],
    '18': [[False, False, False, True], [True, False, False, False], [False, False, False, False], [False, False, False, False]],
    '19': [[True, False, False, False], [True, False, True, False], [False, False, True, False], [False, False, False, False]],
    '20': [[False, False, False, True], [False, False, False, False], [False, False, False, False], [False, False, False, False]],
    '21': [[True, False, False, False], [True, False, True, True], [False, False, True, True], [False, False, False, False]],
    '22': [[False, False, False, False], [True, False, False, False], [True, False, False, False], [False, False, False, False]],
    '23': [[True, True, False, True], [True, True, False, True], [False, False, False, False], [False, False, False, False]],
    '24': [[True, False, False, False], [False, False, False, True], [False, False, False, False], [False, False, False, False]],
    '25': [[False, False, True, True], [False, False, True, True], [False, False, False, False], [False, False, False, False]],
    '26': [[False, False, False, False], [True, True, False, False], [True, True, False, False], [True, True, False, False]],
    '27': [[True, True, False, True], [False, False, False, False], [False, False, False, False], [False, False, False, False]],
    '28': [[], [], [], []],
    '29': [[], [], [], []],
    '30': [[], [], [], []],
    '31': [[], [], [], []],
    '32': [[], [], [], []],
    '33': [[], [], [], []],
    '34': [[], [], [], []],
    '35': [[], [], [], []],
    '36': [[], [], [], []],
    '37': [[], [], [], []],
    '38': [[], [], [], []],
    '39': [[], [], [], []],
    '40': [[], [], [], []],
    '41': [[], [], [], []],
    '42': [[], [], [], []],
    '43': [[], [], [], []],
    '44': [[], [], [], []],
    '45': [[], [], [], []],
    '46': [[], [], [], []],
    '47': [[], [], [], []],
    '48': [[], [], [], []],
    '49': [[], [], [], []],
    '50': [[], [], [], []]
}
